### PR TITLE
Convert app to use CRNA

### PR DESCRIPTION
**Pull request by brentvatne**
As discussed on Twitter, this converts the project to use CRNA. Clone, run `yarn`, then `yarn ios` or `yarn android` to get going. Or, `yarn start` to see QR code and scan from Expo app on your phone. Deleted ios/android directories as they are no longer used. You can re-generate them if you want to demonstrate adding native dependencies by ejecting.

### CODE REVIEW

**Comment by brentvatne** [comment]
React Native docs now include CRNA in quick start so this makes even more sense :)

screen shot 2017-06-09 at 11 22 41 am

**Comment by brentvatne** [comment]
@dabit3 - is there still interest in this or should I close the PR?

**Comment by dabit3** [comment]
@brentvatne Hey, sorry been busy the past couple of weeks! I'll merge this weekend, and lyk if I have any questions :) Thanks again!

**Comment by brentvatne** [comment]
sounds good, I'll update this to latest version and resolve conflicts then

**Comment by dabit3** [comment]
@brentvatne hey, I know you're busy, just pinging you :)

**Comment by brentvatne** [comment]
heya @dabit3 - didn't get a chance to update over the weekend as I was moving, updating it now!

**Comment by brentvatne** [comment]
@dabit3 - updated! working well on react-native 0.45.1 :)

**Comment by dabit3** [comment]
Thanks so much @brentvatne, this will also help in my intro to Expo that I usually give in my trainings!

**Pull request merged**
